disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - multiple_closures_with_trailing_closure
  - function_parameter_count
  - identifier_name
  - vertical_whitespace
  - trailing_newline
  - unused_closure_parameter
  - legacy_constructor
  - block_based_kvo
  - vertical_parameter_alignment
  - class_delegate_protocol
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Moop
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 300
# they can set both implicitly with an array
type_body_length:
  - 400 # warning
  - 500 # error
# function_body_length: 80
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    warning: 2
    error: 1 # only error
  excluded: # excluded via string array
    - id
    - Id
    - ID
    - URL
    - GlobalAPIKey
cyclomatic_complexity:
  warning: 25
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
large_tuple:
  warning: 5 
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
